.SILENT:
all:
	javac -classpath "mongo-2.7.2.jar" *.java


run:
	#java -classpath ":mongo-2.7.2.jar" MongoClient pp 
	java -classpath ":mongo-2.7.2.jar" MongoClient narmada ../../../../ZachsBenchMarkData/censusdata/censusdata.sample.2GB

#small-census

#data.sample
#-d mongoclient_classes/ *.java
